# SPDX-License-Identifier: PMPL-1.0-or-later
# SPDX-FileCopyrightText: 2024-2026 Jonathan D.A. Jewell and Contributors

[project]
name = "LolAnalysis"
uuid = "a3f1b2c4-d5e6-7f89-0a1b-2c3d4e5f6789"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
Clustering = "aabd7145-8216-542d-afb2-2a83900db5b6"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InformationMeasures = "96684042-fbee-5c2e-80c4-e47002d88a5a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringEncodings = "69024149-9ee7-5d6a-999f-4136abab0b93"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc3c0161571"
WordTokenizers = "796a5d58-b03d-544a-977e-18c17f187ber"
