# Example Hugo configuration for Palimpsest License
# Add these parameters to your config.toml

[params.palimpsest]
  version = "0.4"
  licenseUrl = "https://palimpsestlicense.org/v0.4"
  workTitle = "My Hugo Site"
  author = "Your Name"
  agiConsentRequired = true
  emotionalLineage = "A personal blog exploring technology and ethics"

# Then include the partials in your layout files:
# In layouts/_default/baseof.html:
#
# <head>
#   {{ partial "palimpsest-meta.html" . }}
# </head>
# <body>
#   ...
#   {{ partial "palimpsest-jsonld.html" . }}
# </body>
